spring:
  application:
    name: networking1
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URI}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost:3306/networking?useSSL=false&serverTimezone=Asia/Seoul
#    username: root
#    password: 0726

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/cotatonetworking
    username: sa
    password:

logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

