#spring:
#  application:
#    name: networking1
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URI}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQLDialect

#logging:
#    level:
#      org:
#        hibernate:
#          type:
#            descriptor:
#              sql: trace
#

spring:
  application:
    name: networking1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URI}?rewriteBatchedStatements=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
      order_inserts: true
      order_updates: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
